name: logstream
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 41234:41234/udp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/queue_health"]
      interval: 10s
    env_file:
      - path: ./default.env
        required: true
      - path: ./override.env
        required: false
    depends_on:
      - pgvector
      - valkey
  webui: 
    build:
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - 7860:7860
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 10s
    env_file:
      - path: default.env
        required: true
      - path: override.env
        required: false
    depends_on:
      app: 
        condition: service_healthy

  # Backend Services
  pgvector:
    image: pgvector/pgvector:pg16
    env_file:
      - path: default.env
        required: true
      - path: override.env
        required: false
    volumes:
      - ./runtime-data/pgvector:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 7861:8080
    environment:
      - ADMINER_DEFAULT_SERVER=pgvector
  valkey:
    image: valkey/valkey:7.2
    volumes:
      - ./runtime-data/valkey:/data